name: postgres
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=simpledb
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
